### ISSUE TITLE
406 Not Acceptable

### ISSUE THREAD

**Issue by eminetto** [andygrunwald/cachet#1]
I'm receiving this error when running the tests:

```
--- FAIL: ExampleGeneralService_Ping (0.66s)
panic: API call to https://demo.cachethq.io/api/v1/ping failed: 406 Not Acceptable [recovered]
    panic: API call to https://demo.cachethq.io/api/v1/ping failed: 406 Not Acceptable

goroutine 1 [running]:
testing.runExample.func2(0xece73579b, 0xc8097b5a36, 0x56b520, 0xc8200b63f0, 0xc820032010, 0xc8201e7500, 0x3f5480, 0x1a, 0x447750, 0x3f5a20, ...)
    /usr/local/Cellar/go/1.5.3/libexec/src/testing/example.go:93 +0x3f9
github.com/andygrunwald/cachet_test.ExampleGeneralService_Ping()
    /Users/eminetto/Documents/Projects/moveis-simonetti/consulta-cpf-cnpj-server/src/github.com/andygrunwald/cachet/cachet_example_test.go:16 +0xf7
testing.runExample(0x3f5480, 0x1a, 0x447750, 0x3f5a20, 0x1d, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/testing/example.go:98 +0x3cb
testing.RunExamples(0x447778, 0x567660, 0x2, 0x2, 0xf7301)
    /usr/local/Cellar/go/1.5.3/libexec/src/testing/example.go:36 +0x31b
testing.(*M).Run(0xc820063ef8, 0xf74a3)
    /usr/local/Cellar/go/1.5.3/libexec/src/testing/testing.go:495 +0xac
main.main()
    github.com/andygrunwald/cachet/_test/_testmain.go:132 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 227 [runnable]:
syscall.Syscall(0x6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.Close(0x6, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/syscall/zsyscall_darwin_amd64.go:404 +0x4a
net.(*netFD).destroy(0xc8201fcfc0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:135 +0x46
net.(*netFD).decref(0xc8201fcfc0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:153 +0x40
net.(*netFD).Close(0xc8201fcfc0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:199 +0x87
net.(*conn).Close(0xc8200d64d8, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:196 +0xab
crypto/tls.(*Conn).Close(0xc8200e8b00, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:953 +0xe3
net/http.(*persistConn).closeLocked(0xc820155600)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1248 +0x4e
net/http.(*persistConn).close(0xc820155600)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1242 +0x7a
net/http.(*persistConn).readLoop(0xc820155600)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1004 +0x954
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:685 +0xc78

goroutine 228 [select]:
net/http.(*persistConn).writeLoop(0xc820155600)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:686 +0xc9d
exit status 2
FAIL    github.com/andygrunwald/cachet  0.696s
```

My go version is go1.5.3 darwin/amd64

**Comment by andygrunwald** [comment]
Hm. This is strange.
During debugging this issue i stumbled upon another issue. See https://github.com/CachetHQ/Cachet/issues/1658
But this was fixed in https://github.com/andygrunwald/cachet/commit/ea39fbd6039692eb9413958d1cdfcbcdcad4f285

Further more i added golang 1.4 and golang 1.5 into travis config. See https://travis-ci.org/andygrunwald/cachet/builds/118558156

Can you still reproduce this?
